"""phdb.plugins.session_buddy — scaffold-generated source plugin.

Generated by ``phdb plugin scaffold``. Fill in ``plugin.py`` to
make this plugin do real work.
"""

from __future__ import annotations

from phdb.plugins.session_buddy.plugin import SessionBuddyPlugin

__all__ = ["SessionBuddyPlugin"]
