"""DB_SCHEMA.md regeneration — Phase 6 of the phdb Plugin Architecture plan.

Walks the ``phdb.schemas`` registry, queries ``sqlite_master`` for live
table shapes, and consults plugin manifests for "which plugins emit
which @type" attributions. Emits a flat-text Markdown summary grouped
by Schema.org ``@type``.

CLI surface:
    phdb schema regenerate              # rebuild DB_SCHEMA.md
    phdb schema regenerate --dry-run    # print to stdout instead
    phdb schema regenerate --output X   # write to X instead of DB_SCHEMA.md
    phdb schema diff                    # show the live-vs-declared diff

Wired into ``phdb ingest`` as a post-ingest hook — runs unless
``--no-schema-regen`` is passed.
"""

from __future__ import annotations

import sqlite3
from collections import defaultdict
from collections.abc import Iterable
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

from phdb.core.plugin import discover_facets, discover_plugins
from phdb.schemas import all_schemas
from phdb.schemas.base import EntitySchema, Schema


@dataclass(frozen=True)
class TableRowCount:
    table: str
    count: int


def _row_counts(conn: sqlite3.Connection, schemas: Iterable[type[Schema]]) -> dict[str, int]:
    """Return {table: count} for every declared table that exists live."""
    out: dict[str, int] = {}
    for schema in schemas:
        try:
            r = conn.execute(f"SELECT COUNT(*) FROM [{schema.table_name}]").fetchone()
            out[schema.table_name] = int(r[0]) if r else 0
        except sqlite3.OperationalError:
            out[schema.table_name] = 0
    return out


def _plugin_emitters_by_type() -> dict[str, list[str]]:
    """Return {@type: [plugin_name, ...]} from installed source plugins' manifests."""
    emitters: dict[str, list[str]] = defaultdict(list)
    for d in discover_plugins():
        if d.manifest.source is None:
            continue
        for schema_type in d.manifest.source.emits:
            emitters[schema_type].append(d.name)
    return emitters


def _facet_consumers_by_type() -> dict[str, list[str]]:
    """Return {facet_type: [plugin_name, ...]} from installed facet plugins."""
    out: dict[str, list[str]] = defaultdict(list)
    for d in discover_facets():
        if d.manifest.facet is None:
            continue
        out[d.manifest.facet.consumes].append(d.name)
    return out


def regenerate(conn: sqlite3.Connection | None = None) -> str:
    """Build the DB_SCHEMA.md content as a string.

    If ``conn`` is provided, row counts come from the live DB; otherwise
    counts are omitted.
    """
    schemas = list(all_schemas())
    schemas.sort(key=lambda s: (
        0 if issubclass(s, EntitySchema) else 1,
        s.table_name,
    ))
    counts: dict[str, int] = {}
    if conn is not None:
        counts = _row_counts(conn, schemas)
    emitters = _plugin_emitters_by_type()
    facet_consumers = _facet_consumers_by_type()

    lines: list[str] = []
    lines.append("# DB_SCHEMA.md — Personal History Database (regenerated)")
    lines.append("")
    lines.append("> Auto-regenerated by `phdb schema regenerate`. Edits to this file")
    lines.append("> are overwritten on next ingest. Schema descriptions and column")
    lines.append("> notes live on the dataclass schemas in `phdb.schemas.canonical`.")
    lines.append("")
    lines.append(f"**Regenerated at:** {datetime.now(UTC).strftime('%Y-%m-%dT%H:%M:%SZ')}")
    lines.append("")

    # Entity schemas
    entity_schemas: list[type[EntitySchema]] = [
        s for s in schemas if issubclass(s, EntitySchema)
    ]
    if entity_schemas:
        lines.append("## Entity tables")
        lines.append("")
        lines.append("Identity-bearing schemas — one row per ``dedup_key`` value.")
        lines.append("Action rows FK to these via the auto-generated ``<entity>_id`` column.")
        lines.append("")
        lines.append("| Table | @type | Rows | dedup_key | Plugins |")
        lines.append("|:---|:---|---:|:---|:---|")
        for es in entity_schemas:
            row_count = counts.get(es.table_name, 0)
            plugins = ", ".join(emitters.get(es.schema_type, [])) or "—"
            lines.append(
                f"| `{es.table_name}` | {es.schema_type} | {row_count:,} | "
                f"`{es.dedup_key}` | {plugins} |"
            )
        lines.append("")

    # Action schemas
    action_schemas = [s for s in schemas if not issubclass(s, EntitySchema)]
    if action_schemas:
        lines.append("## Action / document tables")
        lines.append("")
        lines.append("Event-shaped + document-shaped schemas. Plugins listed below")
        lines.append("declare ``emits = [<@type>]`` in their manifest.")
        lines.append("")
        lines.append("| Table | @type | Rows | Date column | Plugins |")
        lines.append("|:---|:---|---:|:---|:---|")
        for as_ in action_schemas:
            row_count = counts.get(as_.table_name, 0)
            plugins = ", ".join(emitters.get(as_.schema_type, [])) or "—"
            date_col = as_.date_column or "—"
            lines.append(
                f"| `{as_.table_name}` | {as_.schema_type} | {row_count:,} | "
                f"`{date_col}` | {plugins} |"
            )
        lines.append("")

    # Facet plugins
    if facet_consumers:
        lines.append("## Facet plugins")
        lines.append("")
        lines.append("Facet plugins subscribe to source-plugin emissions via the")
        lines.append("``EmissionBus`` and project them into a facet node graph.")
        lines.append("")
        lines.append("| Plugin | Consumes | Node table |")
        lines.append("|:---|:---|:---|")
        for facet_type, plugin_names in sorted(facet_consumers.items()):
            for plugin_name in plugin_names:
                desc = next(
                    (d for d in discover_facets() if d.name == plugin_name),
                    None,
                )
                node_table = desc.manifest.facet.node_table if desc and desc.manifest.facet else "—"
                lines.append(f"| `{plugin_name}` | {facet_type} | `{node_table}` |")
        lines.append("")

    # Per-table column detail
    lines.append("## Column detail")
    lines.append("")
    for s in schemas:
        lines.append(f"### `{s.table_name}` — {s.schema_type}")
        if s.description:
            lines.append("")
            lines.append(s.description.strip())
        lines.append("")
        lines.append("| Column | Type | Null | PK | Default |")
        lines.append("|:---|:---|:---:|:---:|:---|")
        for f in s.all_fields():
            null = "no" if not f.nullable else "yes"
            pk = "yes" if f.primary_key else ""
            default = f.default or ""
            lines.append(
                f"| `{f.name}` | {f.sql_type} | {null} | {pk} | {default} |"
            )
        if s.all_indexes():
            lines.append("")
            lines.append("Indexes:")
            for idx in s.all_indexes():
                unique = "UNIQUE " if idx.unique else ""
                cols = ", ".join(idx.columns)
                where = f" WHERE {idx.where_clause}" if idx.where_clause else ""
                lines.append(f"- `{idx.name}` — {unique}({cols}){where}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def diff_against_live(conn: sqlite3.Connection) -> list[str]:
    """Return a list of human-readable drift lines comparing declared vs live."""
    from phdb.schemas.migration import diff_schema

    out: list[str] = []
    for schema in all_schemas():
        d = diff_schema(conn, schema)
        if d.clean:
            continue
        out.append(f"# {schema.table_name} ({schema.schema_type})")
        if d.table_missing:
            out.append("  table is missing entirely from live DB")
            continue
        for col in d.missing_columns:
            out.append(f"  + add column: {col.column_ddl()}")
        for idx_name in d.missing_indexes:
            out.append(f"  + add index: {idx_name}")
        for col_name in d.extra_columns:
            out.append(f"  ? extra live column not in schema: {col_name}")
        for idx_name in d.extra_indexes:
            out.append(f"  ? extra live index not in schema: {idx_name}")
        for col_name, expected, actual in d.type_mismatches:
            out.append(f"  ! type mismatch on {col_name}: expected {expected}, live {actual}")
    return out


def write_to_file(path: Path, conn: sqlite3.Connection | None = None) -> Path:
    """Write the regenerated content to ``path``. Returns the path."""
    content = regenerate(conn)
    path.write_text(content, encoding="utf-8")
    return path


DEFAULT_OUTPUT_PATH = Path("DB_SCHEMA.md")


__all__ = [
    "DEFAULT_OUTPUT_PATH",
    "diff_against_live",
    "regenerate",
    "write_to_file",
]
